import type { Metadata } from "next";
import "./globals.css";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Services from "@/components/Services";
import Contactus from "@/components/Contactus";
import Gallery from "@/components/Gallery";
import Footer from "@/components/Footer";

// import Gallery from "@/components/Gallery";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
      />
      <body>
        <Hero />
        {children}
        <About />
        <Services />
        <Gallery />
        <Contactus />
        <Footer />
      </body>
    </html>
  );
}
